image: daewok/lisp-devel

stages:
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  - git clone https://github.com/sionescu/bordeaux-threads.git ~/quicklisp/local-projects/bordeaux-threads
  - git clone https://gitlab.com/ediethelm/trivial-utilities.git ~/quicklisp/local-projects/trivial-utilities
  - git clone https://gitlab.com/ediethelm/trivial-object-lock.git ~/quicklisp/local-projects/trivial-object-lock
  - cp -r /builds/ediethelm/trivial-pooled-database ~/quicklisp/local-projects/

sbcl-build:
  stage: build
  script:
    - sbcl --non-interactive --eval "(ql:quickload :trivial-pooled-database)"


ccl-build:
  stage: build
  script:
    - ccl --eval "(let ((*debugger-hook* (lambda (c m)
                                           (declare (ignore c m))
                                           (uiop:quit 1))))
                    (ql:quickload :trivial-pooled-database))"
